import { makeStyles } from "@material-ui/core";
import mq from "../../../config/mq";
const useStyles = makeStyles((theme) => ({
    cabezera:{
        margin:0,
        padding:0,
        width:'912px',
    }, 
    
    let:{
        fontSize:'12px',
    },
    leta:{
        fontSize:'14px',
    },
    p:{
        width:'887px',
        height:'43px',
        padding:'0px 0px 0px 0px ',
        border:0,
    },
    titleStyle:{
        backgroundColor:'#F3F6F9',        
        borderRadius:'6px',
        marginTop:'10px',
        marginLeft:'11px',
        marginRight:'14px',
        display:'flex', 
    },
    boxStyle:{
        backgroundColor:'red',
        width:'41px',
        display:'flex',
    },
    TableHeadbox:{
        display: 'contents',
        flexDirection: 'left',
        width:'60.78px',
        height:'18px',
        padding: 10,
        bgcolor: 'pink',
        border: '1px solid red',
        borderRadius: 2,
        fontSize: '0.875rem',
        fontWeight: '700',
    },
    TableHeadbox1:{
        display: 'contents',
        flexDirection: 'left',
        width:'41px',
        height:'18px',
        backgroundColor:'blue',
    },
    TableHeadbox2:{
        display: 'contents',
        flexDirection: 'left',
        width:'50.65px',
        height:'18px',
        backgroundColor:'blue',
    },
    TableHeadbox3:{
        display: 'contents',
        width:'50.65px',
        flexDirection: 'left',
        height:'18px',
        backgroundColor:'blue',
    },
    TableHeadbox4:{
        display: 'contents',
        flexDirection: 'left',
        width:'50.65px',
        height:'18px',
        backgroundColor:'blue',
    },
    TableHeadbox5:{
        display: 'contents',
        flexDirection: 'left',
        width:'50.65px',
        height:'18px',
        backgroundColor:'blue',
    },
    TableHeadboxStyle1:{
        backgroundColor:'red',
        width:'41px',
        display:'flex',
        flexDirection:'column',
    },
    TableHeadstyletexto:{
        padding: '12px 59.75px 13px 28.08px',
        height:'43px',
        fontSize:'12px',
        lineHeight:'18px',
        fontWeight:600,
        color:'#000000',
    },
    TableHeadstyletexto1:{
        width:'41px',
        height:'43px',
        padding: '12px 125.73px 13px 0px ',
        fontSize:'12px',
        lineHeight:'18px',
        fontWeight:600,
        color:'#000000',
    },
    TableHeadstyletexto2:{
        width:'50.65px',
        height:'43px',
        padding: '12px 119.01px 13px 0px',
        fontSize:'12px',
        lineHeight:'18px',
        
        fontWeight:600,
        color:'#000000',
    },
    TableHeadstyletexto3:{
        
        width:'70px',
        height:'43px',
        padding: '12px 233.35px 13px 0px',
        fontSize:'12px',
        lineHeight:'18px',
        
        fontWeight:600,
        color:'#000000',
    },
    TableHeadstyletexto4:{
        width:'66px',
        height:'43px',
        fontSize:'12px',
        padding: '12px 100px 13px 0px',
        lineHeight:'18px',
        fontWeight:600,
        color:'#000000',
    },
    TableHeadstyletexto5:{
        width:'88px',
        height:'43px',
        fontSize:'12px',
        padding: '12px 109.43px 13px 31.8px',
        lineHeight:'18px',

        fontWeight:600,
        color:'#000000',
    },
    stylebody:{
        backgroundColor:'red',
        padding: '0px 24px 0px 24px',
    },
    TableBodybox:{
        display: 'contents',
        flexDirection: 'left',
        width:'62px',
        height:'21px',
        padding: 10,
        bgcolor: 'pink',
        border: '1px solid red',
        borderRadius: 2,
        fontSize: '0.875rem',
        fontWeight: '700',
    },
    TableBodybox1:{
        display: 'contents',
        flexDirection: 'left',
        width:'41px',
        height:'18px',
        backgroundColor:'blue',
    },
    TableBodybox2:{
        display: 'contents',
        flexDirection: 'left',
        width:'240px',
        height:'auto',
        
        backgroundColor:'blue',
    },
    box3:{
        display: 'contents',
        width:'242px',
        flexDirection: 'left',
        maxWidth:'240px',

        backgroundColor:'blue',
    },
    TableBodybox4:{
        display: 'contents',
        flexDirection: 'left',
        width:'50.65px',
        height:'18px',
        
        backgroundColor:'blue',
    },
    TableBodybox5:{
        display: 'contents',
        flexDirection: 'left',
        width:'50.65px',
        height:'18px',
        backgroundColor:'blue',
    },
    TableBodyboxStyle1:{
        backgroundColor:'red',
        width:'41px',
        display:'flex',
        flexDirection:'column',
    },
    TableBodystyletexto:{
        padding: '17px 58.86px 26px 30px',
        height:'18px',
        fontSize:'12px',
        lineHeight:'18px',
        fontWeight:600,
        color:'#000000',
    },
    TableBodystyletexto1:{
        width:'41px',
        heigth:'18px',
        padding: '17px 130.73px 0px 0px ',
        fontSize:'12px',
        lineHeight:'18px',
        fontWeight:600,
        color:'#000000',
    },
    TableBodystyletexto2:{
        width:'50.65px',
        height:'18px',
        padding: '17px 130.01px 0px 0px',
        fontSize:'12px',
        lineHeight:'18px',
        fontWeight:600,
        color:'#000000',
    },
    body2:{
        margin:'10px',
        backgroundColor:'red',
    },
    TableBodystyletexto3:{
        width:'242px',
        padding: '8.5px 50px 10.5px 0px',
        fontSize:'10px',
        fontWeight:500,
        color:'#000000',
    },
    TableBodystyletexto4:{
        width:'66px',
        height:'18px',
        fontSize:'12px',
        padding: '17px 100px 0px 10px',
        lineHeight:'18px',
        fontWeight:600,
        color:'#000000',
    },
    TableBodystyletexto5:{
        width:'88px',
        height:'18px',
        fontSize:'12px',
        padding: '17px 109.43px 0px 15.8px',
        lineHeight:'18px',
        fontWeight:600,
        color:'#000000',
    },
    TableBodyDivider:{
        width:'840px',
        height:'1px',
        marginLeft:'31px',
        marginRight:'21px',
    },
}));
export default useStyles;
