import { makeStyles } from "@material-ui/core";
import mq from "../../../config/mq";
const useStyles = makeStyles((theme) => ({
<<<<<<< HEAD
    boxContainer:{
        width:'912px',
        // background:'skyblue',
        height:'587px',
        margin:'0px',
        padding:'0px',
    }, 
    boxTable:{
        width:'912px',
        // background:'red',
    }, 
=======
    cabezera:{
        margin:0,
        padding:0,
        width:'912px',
    }, 
    
>>>>>>> 4f158bd19a70584a1352ff6855ae646539b582e0
    let:{
        fontSize:'12px',
    },
    leta:{
        fontSize:'14px',
    },
    p:{
<<<<<<< HEAD
        width:'854px',
        height:'43px',
        border:0,
    },
    titleStyle:{
        width:'887px',
        backgroundColor:'#F3F6F9',  
        background:'yellow',      
=======
        width:'887px',
        height:'43px',
        padding:'0px 0px 0px 0px ',
        border:0,
    },
    titleStyle:{
        backgroundColor:'#F3F6F9',        
>>>>>>> 4f158bd19a70584a1352ff6855ae646539b582e0
        borderRadius:'6px',
        marginTop:'10px',
        marginLeft:'11px',
        marginRight:'14px',
        display:'flex', 
    },
    boxStyle:{
        backgroundColor:'red',
        width:'41px',
        display:'flex',
    },
    TableHeadbox:{
        display: 'contents',
        flexDirection: 'left',
        width:'60.78px',
        height:'18px',
<<<<<<< HEAD
        // padding: 10,
=======
        padding: 10,
>>>>>>> 4f158bd19a70584a1352ff6855ae646539b582e0
        bgcolor: 'pink',
        border: '1px solid red',
        borderRadius: 2,
        fontSize: '0.875rem',
        fontWeight: '700',
    },
<<<<<<< HEAD
    TableHeadboxStyle1:{
        background:'red',
=======
    TableHeadbox1:{
        display: 'contents',
        flexDirection: 'left',
        width:'41px',
        height:'18px',
        backgroundColor:'blue',
    },
    TableHeadbox2:{
        display: 'contents',
        flexDirection: 'left',
        width:'50.65px',
        height:'18px',
        backgroundColor:'blue',
    },
    TableHeadbox3:{
        display: 'contents',
        width:'50.65px',
        flexDirection: 'left',
        height:'18px',
        backgroundColor:'blue',
    },
    TableHeadbox4:{
        display: 'contents',
        flexDirection: 'left',
        width:'50.65px',
        height:'18px',
        backgroundColor:'blue',
    },
    TableHeadbox5:{
        display: 'contents',
        flexDirection: 'left',
        width:'50.65px',
        height:'18px',
        backgroundColor:'blue',
    },
    TableHeadboxStyle1:{
        backgroundColor:'red',
>>>>>>> 4f158bd19a70584a1352ff6855ae646539b582e0
        width:'41px',
        display:'flex',
        flexDirection:'column',
    },
    TableHeadstyletexto:{
<<<<<<< HEAD
        height:'18px',
        width:'60.779px',
        marginLeft:'20.08px',
        marginTop:'12px',
        marginBlock:'13px',
        marginRight:'59.75px',
        fontSize:'12px',
        lineHeight:'normal',
        fontFamily: "Poppins-Regular",
        fontWeight:600,
        color:'#464E5F',
        fontStyle:'normal',
        letterSpacing:'0.36px',
    },
    TableHeadstyletexto1:{
        width:'41px',
        height:'18px',
        marginLeft:'0px',
        marginTop:'12px',
        marginBlock:'13px',
        marginRight:'84.73px',
        fontSize:'12px',
        fontFamily: "Poppins-Regular",
        lineHeight:'normal',
        fontStyle:'normal',
        letterSpacing:'0.36px',
        fontWeight:600,
        color:'#464E5F',
    },
    TableHeadstyletexto2:{
        width:'50.649px',
        height:'18px',
        marginLeft:'0px',
        marginTop:'12px',
        marginBlock:'13px',
        marginRight:'69.01px',
        fontSize:'12px',
        lineHeight:'normal',
        fontFamily: "Poppins-Regular",
        letterSpacing:'0.36px',
=======
        padding: '12px 59.75px 13px 28.08px',
        height:'43px',
        fontSize:'12px',
        lineHeight:'18px',
        fontWeight:600,
        color:'#000000',
    },
    TableHeadstyletexto1:{
        width:'41px',
        height:'43px',
        padding: '12px 125.73px 13px 0px ',
        fontSize:'12px',
        lineHeight:'18px',
        fontWeight:600,
        color:'#000000',
    },
    TableHeadstyletexto2:{
        width:'50.65px',
        height:'43px',
        padding: '12px 119.01px 13px 0px',
        fontSize:'12px',
        lineHeight:'18px',
        
>>>>>>> 4f158bd19a70584a1352ff6855ae646539b582e0
        fontWeight:600,
        color:'#000000',
    },
    TableHeadstyletexto3:{
<<<<<<< HEAD
        width:'242px',
        height:'18px',
        marginLeft:'0px',
        marginTop:'12px',
        marginBlock:'14px',
        marginRight:'42.31px',
        fontSize:'12px',
        fontStyle:'normal',
        lineHeight:'normal',
        letterSpacing:'0.36px',
        fontFamily: "Poppins-Regular",
        fontWeight:600,
        color:'#000 ',
    },
    TableHeadstyletexto4:{
        width:'66px',
        height:'18px',
        marginLeft:'0px',
        marginTop:'12px',
        marginBlock:'13px',
        marginRight:'43.43px',
        fontSize:'12px',
        fontStyle:'normal',
        lineHeight:'normal',
        letterSpacing:'0.36px',
        fontFamily: "Poppins-Regular",
=======
        
        width:'70px',
        height:'43px',
        padding: '12px 233.35px 13px 0px',
        fontSize:'12px',
        lineHeight:'18px',
        
        fontWeight:600,
        color:'#000000',
    },
    TableHeadstyletexto4:{
        width:'66px',
        height:'43px',
        fontSize:'12px',
        padding: '12px 100px 13px 0px',
        lineHeight:'18px',
>>>>>>> 4f158bd19a70584a1352ff6855ae646539b582e0
        fontWeight:600,
        color:'#000000',
    },
    TableHeadstyletexto5:{
        width:'88px',
<<<<<<< HEAD
        height:'18px',
        fontSize:'12px',
        marginLeft:'0px',
        marginTop:'12px',
        marginBlock:'13px',
        marginRight:'19.26px',
        fontStyle:'normal',
        lineHeight:'normal',
        fontFamily: "Poppins-Regular",
        fontWeight:600,
        letterSpacing:'0.36px',
=======
        height:'43px',
        fontSize:'12px',
        padding: '12px 109.43px 13px 31.8px',
        lineHeight:'18px',

        fontWeight:600,
>>>>>>> 4f158bd19a70584a1352ff6855ae646539b582e0
        color:'#000000',
    },
    stylebody:{
        backgroundColor:'red',
        padding: '0px 24px 0px 24px',
    },
    TableBodybox:{
        display: 'contents',
        flexDirection: 'left',
        width:'62px',
        height:'21px',
        padding: 10,
        bgcolor: 'pink',
        border: '1px solid red',
        borderRadius: 2,
        fontSize: '0.875rem',
        fontWeight: '700',
    },
    TableBodybox1:{
        display: 'contents',
        flexDirection: 'left',
        width:'41px',
        height:'18px',
        backgroundColor:'blue',
    },
    TableBodybox2:{
        display: 'contents',
        flexDirection: 'left',
        width:'240px',
        height:'auto',
        
        backgroundColor:'blue',
    },
    box3:{
        display: 'contents',
        width:'242px',
        flexDirection: 'left',
        maxWidth:'240px',

        backgroundColor:'blue',
    },
    TableBodybox4:{
        display: 'contents',
        flexDirection: 'left',
        width:'50.65px',
        height:'18px',
        
        backgroundColor:'blue',
    },
    TableBodybox5:{
        display: 'contents',
        flexDirection: 'left',
        width:'50.65px',
        height:'18px',
        backgroundColor:'blue',
    },
    TableBodyboxStyle1:{
        backgroundColor:'red',
        width:'41px',
        display:'flex',
        flexDirection:'column',
    },
    TableBodystyletexto:{
        padding: '17px 58.86px 26px 30px',
        height:'18px',
        fontSize:'12px',
        lineHeight:'18px',
        fontWeight:600,
        color:'#000000',
    },
    TableBodystyletexto1:{
        width:'41px',
        heigth:'18px',
        padding: '17px 130.73px 0px 0px ',
        fontSize:'12px',
        lineHeight:'18px',
        fontWeight:600,
        color:'#000000',
    },
    TableBodystyletexto2:{
        width:'50.65px',
        height:'18px',
        padding: '17px 130.01px 0px 0px',
        fontSize:'12px',
        lineHeight:'18px',
        fontWeight:600,
        color:'#000000',
    },
    body2:{
        margin:'10px',
        backgroundColor:'red',
    },
    TableBodystyletexto3:{
        width:'242px',
        padding: '8.5px 50px 10.5px 0px',
        fontSize:'10px',
        fontWeight:500,
        color:'#000000',
    },
    TableBodystyletexto4:{
        width:'66px',
        height:'18px',
        fontSize:'12px',
        padding: '17px 100px 0px 10px',
        lineHeight:'18px',
        fontWeight:600,
        color:'#000000',
    },
    TableBodystyletexto5:{
        width:'88px',
        height:'18px',
        fontSize:'12px',
        padding: '17px 109.43px 0px 15.8px',
        lineHeight:'18px',
        fontWeight:600,
        color:'#000000',
    },
    TableBodyDivider:{
        width:'840px',
        height:'1px',
        marginLeft:'31px',
        marginRight:'21px',
    },
<<<<<<< HEAD
    Lista:{
        background:'#FFF',
        width:'912px',
        padding:'0px',
        margin:'0px',
        display:'flex',
    },
    listaTexto1:{
        width:'62px',
        height:'21px',
        marginTop:'22.87px',
        marginLeft:'25px',
        marginRight:'43.86px',
        marginBlock:'26px',
        fontSize:'14px',
        fontStyle:'normal',
        lineHeight:'normal',
        fontFamily: "Poppins-Regular",
        fontWeight:400,
        color:'#464E5F',
    },
    listaTexto2:{
        width:'74px',
        height:'21px',
        marginTop:'22.87px',
        marginLeft:'0px',
        marginRight:'63.81px',
        marginBlock:'26px',
        fontSize:'14px',
        fontStyle:'normal',
        lineHeight:'normal',
        fontFamily: "Poppins-Regular",
        fontWeight:400,
        color:'#464E5F',
    },
    listaTexto3:{
        width:'62px',
        height:'18px',
        marginTop:'22.87px',
        marginLeft:'0px',
        marginRight:'64.34px',
        marginBlock:'30px',
        fontSize:'12px',
        fontStyle:'normal',
        lineHeight:'normal',
        fontFamily: "Poppins-Regular",
        fontWeight:500,
        letterSpacing:'-0.12px',
        color:'#464E5F',
    },
    listaTexto4:{
        width:'240px',
        height:'45px',
        marginTop:'12.37px',
        marginLeft:'0px',
        marginRight:'67.81px',
        marginBlock:'10.5px',
        // marginBlock:'10.5',
        fontSize:'10px',
        fontStyle:'normal',
        lineHeight:'normal',
        fontFamily: "Poppins-Regular",
        fontWeight:500,
        color:'#464E5F',
    },
    listaTexto5:{
        width:'17px',
        height:'20px',  
        marginTop:'22.87px',
        marginLeft:'0px',
        marginRight:'88.43px',
        marginBlock:'26px',
        // marginBlock:'10.5',
        fontSize:'13px',
        fontStyle:'normal',
        lineHeight:'normal',
        fontFamily: "Poppins-Regular",
        fontWeight:500,
        color:'#464E5F',
    },
    listaTexto6:{
        width:'49px',
        height:'20px',  
        marginTop:'22.87px',
        marginLeft:'0px',
        marginRight:'51.76px',
        marginBlock:'26px',
        // marginBlock:'10.5',
        fontSize:'13px',
        fontStyle:'normal',
        lineHeight:'normal',
        fontFamily: "Poppins-Regular",
        fontWeight:500,
        color:'#464E5F',
    },
    thodyBox:{
        // background:'gray',
        width:'887px',
    },
    hr:{
        background:'#CDCDCD',
        maxWidth:'860px',
        height:'1px',
        marginLeft:'31px',
        marginRight:'21px',
    },  
=======
>>>>>>> 4f158bd19a70584a1352ff6855ae646539b582e0
}));
export default useStyles;
