import { makeStyles } from "@material-ui/core";

const useStyles = makeStyles((theme) => ({
   base:{
     //    background:'red',
        width:'1248px',
        height: '646px',
        // padding:'10px 20px 30px 40px',
        marginLeft:'96px',
        marginTop: '102px',
        marginRight:'96px',
   },
   confirmacion:{
     //background:'green',
        width:'1248px',
        heigth:'68px',
        display:'flex',
   },
   icon:{
        // height:'20px',
        // width:'20px',
        marginLeft:'39px',
        marginTop:'14px'
   },
   letras:{
        // height:'20px',
        // width:'20px',
        marginLeft:'16px',
        marginTop:'10px',
        marginRight:'31px',
        marginBlock:'10px',
        // marginBlock
   },
   letrasDatos:{
     width:'70px',
     height:'35px',
     fontWeight:'400px',
     marginLeft:'0px',
   },
   containersx:{ 
     maxHeight:'100%',
     maxWidth:'100%',
     marginLeft:'0px',
     // marginTop:'16px',
     padding:'0px',
     // backgroundColor:'pink',
     // padding:'1.063rem 1.375rem 0rem 1.125rem',
     //derecha,derecha,abajo,izquierda  
     },
     sx:{
          // marginTop:'17px',x
          // marginLeft:'0px',
          //marginRight:'0px',
          //padding: '18px',
          display: 'flex',
          flexDirection: 'left',
          height: '421px',
          width:'540px',
          // borderRadius:'0.75rem',
          backgroundColor:'red',
          marginRight:'128px',
     },
     xs:{
          // display: 'flex',
          flexDirection: 'row',
          height: '587px',
          width:'580px',
          backgroundColor:'#FFFFFF',
          padding:'0px 0px',
     },
     datos:{
          display:'flex',
          background:'gray',
     },
     boxPedido:{
          width:'100%',  
          marginLeft:'0px',
          margin:0,
          background:'#fafafa',
     },
     letrasOpciones:{
          // background:'red',
          marginLeft:'180px',
          
     },
     letrasDatos:{
          // background:'red',
          marginLeft:'0px',
          height:'35px',
          width:'70px',
          marginBlock:'10px',
     },
     letrasOpciones1:{
          background:'red',
          marginLeft:'296px',
     },
     letrasDatos1:{
          background:'red',
          marginLeft:'184px',
          height:'107px',
          width:'119px',
          fontSize:'16px',
          fontWeigth:'300px',
          fontHeigth:'27px',
     },
     boxCorreo:{
          display:'flex',
     },
     datosss:{
          display:'flex',
     },
     datosss1:{
          // background:'yellow',
          width:'50%',
     },
     datosss2:{
          // background:'blue',
          width:'50%',
     },
     pedido:{
          // background:'green',
          width:'580px',
          height:'523',
          marginTop:'39px',
     },
     pHeader:{
          // background:'gray',
          display:'flex',
     },
     pHeader1:{
          // background:'yellow',
          marginTop:'39px',
          marginLeft:'59px',
          marginBlock:'18px',
          marginRight:'321px',
          fontSize:'16px',
          fontWeight:'400',
          fontStyle:'normal',
          lineHeight:'27px',
          color:'black',
     },
     pHeader2:{
          // background:'blue',
          marginTop:'39px',
          marginRight:'57px',
          marginBlock:'18px',
     },
     texto1:{
          fontSize:'16px',
          fontWeight:'400',
          fontStyle:'normal',
          lineHeight:'27px',
          color:'black',
     },
     texto2:{
          fontSize:'16px',
          fontWeight:400,
          fontStyle:'normal',
          lineHeight:'27px',
          color:'black',
     },
     texto3:{
          marginTop:'39px',
          fontSize:'16px',
          fontWeight:400,
          fontStyle:'normal',
          lineHeight:'27px',
          color:'black',
     },
     textopedido1:{
          fontSize:'26px',
          fontWeight:400,
          fontStyle:'normal',
          lineHeight:'25px',
          color:'black',
     },
     hr:{
          marginBlock:'10px',
          width:'462px',
     },
     texto4:{
          // background:'yellow',
          marginTop:'15px',
          marginLeft:'59px',
          marginBlock:'18px',
          marginRight:'132px',
          fontSize:'16px',
          fontWeight:'400',
          fontStyle:'normal',
          lineHeight:'27px',
          color:'black',
     },
     texto5:{
          // background:'blue',
          marginTop:'16px',
          marginRight:'156px',
          marginBlock:'18px',
     },
     texto6:{
          // background:'blue',
          marginLeft:'59px',
          marginTop:'15px',
          marginRight:'356px',
          marginBlock:'18px',
     },
     texto7:{
          // background:'blue',
          marginLeft:'59px',
          marginTop:'15px',
          marginRight:'139px',
          marginBlock:'18px',
     },
     texto8:{
          // marginLeft:'59px',
          marginTop:'15px',
          marginRight:'169px',
          marginBlock:'18px',
     },
     texto9:{
          // background:'blue',
          marginLeft:'59px',
          marginTop:'15px',
          marginRight:'374px',
          marginBlock:'18px',
     },
}));
export default useStyles;