import { makeStyles } from "@material-ui/core";

const useStyles = makeStyles((theme) => ({
   base:{
     //    background:'red',
        width:'1248px',
        height: '646px',
        // padding:'10px 20px 30px 40px',
        marginLeft:'96px',
        marginTop: '102px',
        marginRight:'96px',
   },
   confirmacion:{
        background:'#EFEFEF',
        width:'1248px',
        heigth:'68px',
        display:'flex',
        borderRadius: '2px solid red',
   },
   icon:{
        // height:'20px',
        // width:'20px',
        marginLeft:'39px',
        marginTop:'14px'
   },
   letras:{
          // height:'20px',
          // width:'20px',
          marginLeft:'16px',
          marginTop:'10px',
          marginRight:'31px',
          marginBlock:'10px',
          fontFamily: 'DMSans-Regular',
          fontSize: '16px',
          fontStyle: 'normal',
          fontWeight: 400,
          lineHeight: '27px',
        // marginBlock
   },
   letraDatos:{
          width:'70px',
          height:'35px',
          fontFamily: 'DMSans-Regular',
          fontSize: '26px',
          fontStyle: 'normal',
          fontWeight: 400,
          lineHeight: '35px',
          color:"#000000",      
   },
   containersx:{ 
     maxHeight:'100%',
     maxWidth:'100%',
     marginLeft:'0px',
     // marginTop:'16px',
     padding:'0px',
     
     // backgroundColor:'pink',
     // padding:'1.063rem 1.375rem 0rem 1.125rem',
     //derecha,derecha,abajo,izquierda  
     },
     sx:{
          // marginTop:'17px',x
          // marginLeft:'0px',
          //marginRight:'0px',
          //padding: '18px',
          display: 'flex',
          flexDirection: 'left',
          height: '421px',
          width:'540px',
          // borderRadius:'0.75rem',
          //backgroundColor:'red',
          marginRight:'128px',
     },
     xs:{
          // display: 'flex',
          flexDirection: 'row',
          height: '587px',
          width:'580px',
          // backgroundColor:'#FFFFFF',
          padding:'0px 0px',
     },
     datos:{
          display:'flex',
          background:'gray',
     },
     boxPedido:{
          width:'100%',  
          marginLeft:'0px',
          margin:0,
          //backgroundColor: 'red',
          background:'#fafafa',
     },
     letrasOpciones:{
          // background:'red',
          marginLeft:'180px',
          
     },
     letrasDatos:{
          // background:'red',
          marginLeft:'0px',
          height:'35px',
          width:'70px',
          marginBlock:'10px',
     },
     letrasOpciones1:{
          background:'red',
          marginLeft:'296px',
     },
     letrasDatos1:{
          background:'red',
          marginLeft:'184px',
          height:'107px',
          width:'119px',
          fontSize:'16px',
          fontWeigth:'300px',
          fontHeigth:'27px',
     },
     boxCorreo:{
          display:'flex',
     },
     datosss:{
          display:'flex',
          // background:'red',
          marginTop:'26px',
     },
     datosss1:{
          // background:'yellow',
          width:'50%',
     },
     datosss2:{
          // background:'blue',
          width:'50%',
     },
     pedido:{
          background:'#EFEFEF',
          width:'580px',
          height:'523',
          marginTop:'39px',
     },
     container:{
          background:'#EFEFEF',
     },
     pHeader:{
          // background:'gray',
          display:'flex',
          // marginBlock:'16px',
     },
     pHeader1:{
          // background:'yellow',
          marginTop:'39px',
          marginLeft:'59px',
          marginBlock:'18px',
          marginRight:'321px',
          fontFamily:'DMSans-Regular',
          fontSize:'16px',
          fontWeight:'400',
          fontStyle:'normal',
          lineHeight:'27px',
          color:'#000000',
     },
     pHeader2:{
          // background:'blue',
          marginTop:'39px',
          marginRight:'57px',
          marginBlock:'18px',
          fontFamily:'DMSans-Regular',
          fontSize:'16px',
          fontWeight:'400',
          fontStyle:'normal',
          lineHeight:'27px',
          color:'#000000',
     },
     texto1:{
          fontSize:'16px',
          fontWeight:400,
          fontStyle:'normal',
          lineHeight:'27px',
          color:'#000000',
          fontFamily: 'DMSans-Regular',

     },
     texto2:{
          fontSize:'16px',
          fontWeight:400,
          fontStyle:'normal',
          lineHeight:'27px',
          color:'#707070',
          fontFamily: 'DMSans-Regular',
          // marginBlock:'39px',
     },
     texto3:{
          marginTop:'39px',
          fontSize:'16px',
          fontWeight:400,
          fontStyle:'normal',
          lineHeight:'27px',
          color:'#000000',
          fontFamily: 'DMSans-Regular',
     },
     textopedido1:{
          fontSize:'26px',
          fontWeight:400,
          fontStyle:'normal',
          lineHeight:'25px',
          color:'#000000',
          fontFamily: 'DMSans-Regular',
          marginTop:'5px',
          //textTransform: 'uppercase',
     },
     TableBodystyletexto1:{
          // background:'red',
          marginBlock:'26px',
          marginLeft:'59px',
          marginRight:'350px',
          fontFamily: 'DMSans-Regular',
          fontSize: '16px',
          fontStyle: 'normal',
          fontWeight: 400,
          lineHeight: '27px',
          color:'#707070',
     },
     TableBodystyletexto2:{
          // background:'red',
          marginBlock:'26px',
          marginRight:'58px',
          fontFamily: 'DMSans-Regular',
          fontSize: '16px     ',
          fontStyle: 'normal',
          fontWeight: 400,
          lineHeight: '27px',
          color:'#707070',
     },
     hr:{
          marginLeft:'59px',
          marginRigth:'59px',
          width:'462px',
          color:'#D8D8D8',
     },
     texto4:{
          // background:'yellow',
          marginTop:'16px',
          marginLeft:'59px',
          marginRight:'132px',
          marginBlock:'10px',
          fontSize:'16px',
          fontWeight:400,
          fontStyle:'normal',
          lineHeight:'27px',
          color:'#000000',
          fontFamily: 'DMSans-Regular',
     },
     texto5:{
          // background:'blue',
          marginTop:'16px',
          marginRight:'156px',
          marginBlock:'10px',
          color:'#707070',
          fontFamily: 'DMSans-Regular',
          fontSize: '16px',
          fontStyle: 'normal',
          fontWeight: 400,
          lineHeight: '27px',
     },
     texto6:{
          marginTop:'11px',
          marginRight:'59px',
          marginBlock:'15px',
          color:'#707070',
          fontFamily: 'DMSans-Regular',
          fontSize: '16px',
          fontStyle: 'normal',
          fontWeight: 400,
          lineHeight: '27px',
     },
     texto7:{
          marginLeft:'59px',
          marginTop:'16px',
          marginRight:'356px',
          marginBlock:'10px',
          fontFamily: 'DMSans-Regular',
          fontSize: '16px',
          fontStyle: 'normal',
          fontWeight: 400,
          lineHeight: '27px',
          color:'#000000',
     },
     texto8:{
          marginTop:'15px',
          marginRight:'59px',
          marginBlock:'11px',
          fontFamily: 'DMSans-Regular',
          fontSize: '16px',
          fontStyle: 'normal',
          fontWeight: 400,
          lineHeight: '27px',
          color:'#707070'
     },
     texto9:{
          // background:'blue',
          marginTop:'16px',
          marginLeft:'59px',
          marginRight:'139px',
          marginBlock:'10px',
          fontFamily: 'DMSans-Regular',
          fontSize: '16px',
          fontStyle: 'normal',
          fontWeight: 400,
          lineHeight: '27px',
          color:'#000000'
     },
     texto10:{
          // background:'blue',
          marginTop:'13px',
          marginRight:'169px',
          marginBlock:'12px',
          fontFamily: 'DMSans-Regular',
          fontSize: '16px',
          fontStyle: 'normal',
          fontWeight: 400,
          lineHeight: '27px',
          color:'#707070'
     },
     texto11:{
          // background:'blue',
          marginTop:'10px',
          marginRight:'57px',
          marginBlock:'15px',
          fontFamily: 'DMSans-Regular',
          fontSize: '16px',
          fontStyle: 'normal',
          fontWeight: 400,
          lineHeight: '27px',
          color:'#707070'
     },
     texto12:{
          // background:'blue',
          marginLeft:'59px',
          marginTop:'63px',
          marginRight:'374px',
          marginBlock:'30px',
          fontFamily: 'DMSans-Regular',
          fontSize: '16px',
          fontStyle: 'normal',
          fontWeight: 700,
          lineHeight: '27px',
          color:'#000000'
     },
     texto13:{
          marginTop:'63px',
          marginRight:'59px',
          marginBlock:'30px',
          fontFamily: 'DMSans-Regular',
          fontSize: '16px',
          fontStyle: 'normal',
          fontWeight: 700,
          lineHeight: '27px',
          textTransform:'capitalize',
          color:'#000000'
     },
     todo:{
          background:'red',
     },
}));
export default useStyles;